// Plazma Labs — Product Catalog Data
// category keys: tablets, syrups, injections, formulations

const PRODUCTS = [
  // ===== TABLETS & CAPSULES =====
  { name: "AcePlaz-S", rx: true, composition: "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg", form: "Tablet", category: "tablets", area: "pain", image: "assets/products/aceplaz-s.jpg", use: "Pain & Inflammation", tags: ["Traumatic Injury","Post-Surgical Inflammation","Osteoarthritis","Dental Abscess","ENT Inflammation"], also: "AcePlaz-P — Aceclofenac 100mg + Paracetamol 325mg" },
  { name: "AzeePlaz-500", rx: true, composition: "Azithromycin 500mg", form: "Tablet", category: "tablets", area: "infection", image: "assets/products/azeeplaz-500.jpg", use: "Anti-Infective", tags: ["Pharyngitis","Tonsillitis","Sinusitis","Bronchitis","Community Acquired Pneumonia","SSTIs"] },
  { name: "AtPlaz-AM", rx: true, composition: "Amlodipine 5mg + Atenolol 50mg", form: "Tablet", category: "tablets", area: "cardiac", image: "assets/products/atplaz-am.jpg", use: "Cardiac Care", tags: ["Hypertension","Myocardial Infarction","Angina Pectoris","Coronary Heart Disease"] },
  { name: "CalPlan-K2 M", rx: true, composition: "Calcium Citrate 500mg, Zinc 7.5mg, Calcitriol 0.25mcg, Methylcobalamin 1500mcg, Vitamin K2-7 50mcg", form: "Tablet", category: "tablets", area: "bone", image: "assets/products/calplan-k2-m.jpg", use: "Bone & Nerve Health", tags: ["Low Bone Density","Osteoporosis","Hypocalcemia & Fractures","Weak Bones & Muscles"], also: "CalPlan-CT — Calcitriol 0.25mcg + Calcium Carbonate 500mg + Zinc Sulphate Monohydrate 7.5mg Softgel Capsule" },
  { name: "Clindaplaz-300", rx: true, composition: "Clindamycin 300mg", form: "Capsule", category: "tablets", area: "infection", image: "assets/products/clindaplaz-300.jpg", use: "Anti-Infective", tags: ["Cellulitis","Abscess","Preoperative Prophylaxis","RTI & Acute Otitis Media","Bone & Soft Tissue Infections","Endometritis"] },
  { name: "CifiPlaz-O", rx: true, composition: "Cefixime 200mg + Ofloxacin 200mg", form: "Tablet", category: "tablets", area: "infection", image: "assets/products/cifiplaz-o.jpg", use: "Anti-Infective", tags: ["Acute Gastroenteritis","Enteric Fever","UTI","RTIs","Mixed Bacterial Infections"], also: "CifiPlaz-LB 200 — Cefixime 200mg + Lactobacillus 2.5 million spores" },
  { name: "CidoPlaz-200", rx: true, composition: "Cefpodoxime 200mg", form: "Tablet", category: "tablets", area: "infection", image: "assets/products/cidoplaz-200.jpg", use: "Anti-Infective", tags: ["Upper & Lower RTIs","Acute Otitis Media","Sinusitis","UTI","Skin & Soft Tissue Infections"], also: "CidoPlaz-50 — Cefpodoxime Proxetil 50mg Dry Syrup" },
  { name: "DotaCid", rx: true, composition: "Drotaverine 80mg + Mefenamic Acid 250mg", form: "Tablet", category: "tablets", area: "pain", image: "assets/products/dotacid.jpg", use: "Pain & Spasm Relief", tags: ["Renal Colic","Biliary Colic","Dysmenorrhea","Gastrointestinal Colic","Post Surgical Uterine Spasm"] },
  { name: "Dimef-Spas", rx: true, composition: "Mefenamic Acid 250mg + Dicyclomine HCl 10mg", form: "Tablet", category: "tablets", area: "pain", image: "assets/products/dimef-spas.jpg", use: "Pain & Spasm Relief", tags: ["Intestinal Colic","Ureteric Colic","Spasmodic Dysmenorrhea","Biliary Colic","Irritable Bowel Syndrome"] },
  { name: "DoxyPlaz", rx: true, composition: "Doxylamine Succinate 20mg + Pyridoxine 20mg + Folic Acid 5mg", form: "Tablet", category: "tablets", area: "women", image: "assets/products/doxyplaz.jpg", use: "Pregnancy Care", tags: ["Morning Sickness","Hyperemesis Gravidarum","NVP"] },
  { name: "DefPlaz-6", rx: true, composition: "Deflazacort 6mg", form: "Tablet", category: "tablets", area: "pain", image: "assets/products/defplaz-6.jpg", use: "Steroid / Anti-Inflammatory", tags: ["Asthma","Rheumatoid Arthritis","Ulcerative Colitis","Autoimmune Hepatitis","Dermatological Conditions"] },
  { name: "HepaPlaz", rx: false, composition: "L-Ornithine L-Aspartate 250mg + Pancreatin 100mg", form: "Tablet", category: "tablets", area: "gastro", image: "assets/products/hepaplaz.jpg", use: "Liver & Digestive Care", tags: ["Fatty Liver Disease","Post-Alcohol Digestive Disturbance","Loss of Appetite","Hyperammonemia"] },
  { name: "LePlaz-5", rx: true, composition: "Levocetirizine 5mg", form: "Tablet", category: "tablets", area: "respiratory", image: "assets/products/leplaz-5.jpg", use: "Anti-Allergic", tags: ["Seasonal Allergic Rhinitis","Allergic Asthmatic Conditions","Chronic Idiopathic Urticaria","Allergic Dermatitis","Atopic Eczema"] },
  { name: "Montuplaz-L", rx: true, composition: "Levocetirizine 5mg + Montelukast 10mg", form: "Tablet", category: "tablets", area: "respiratory", image: "assets/products/montuplaz-l.jpg", use: "Anti-Allergic / Respiratory", tags: ["Allergic Rhinitis","Seasonal Allergies","Perennial Rhinitis","Allergic Cough","Atopic Eczema"] },
  { name: "MoxiPlaz-CVL 625", rx: false, composition: "Amoxycillin 500mg + Potassium Clavulanate 125mg + Lactobacillus 60 Million spores", form: "Tablet", category: "tablets", area: "infection", image: "assets/products/moxiplaz-cvl-625.jpg", use: "Anti-Infective", tags: ["RTI","SSTI","Pharyngitis & Tonsillitis","Dental Infection","Postoperative Prophylaxis"] },
  { name: "LuCora", rx: true, composition: "Ayurvedic Medicine for Leucorrhoea", form: "Tablet", category: "tablets", area: "women", image: "assets/products/lucora.jpg", use: "Women's Health (Ayurvedic)", tags: ["Leucorrhea","Urinary Tract Infection","Irregular Menstruation","Vaginal Irritation"] },
  { name: "NimPlaz-P", rx: true, composition: "Nimesulide 100mg + Paracetamol 325mg", form: "Tablet", category: "tablets", area: "pain", image: "assets/products/nimplaz-p.jpg", use: "Pain & Inflammation", tags: ["Rheumatoid Arthritis","Musculoskeletal Pain","Low Back Pain","Post-Operative Pain"] },
  { name: "OndePlaz-MD4", rx: true, composition: "Ondansetron 4mg Mouth Dissolving", form: "Tablet", category: "tablets", area: "gastro", image: "assets/products/ondeplaz-md4.jpg", use: "Antiemetic", tags: ["Chemotherapy Induced Nausea & Vomiting","Post-Operative & Post-Radiation N&V","Hyperemesis Gravidarum"] },
  { name: "OfPlaz-D", rx: true, composition: "Omeprazole 20mg + Domperidone 10mg", form: "Capsule", category: "tablets", area: "gastro", image: "assets/products/ofplaz-d.jpg", use: "Gastric Care", tags: ["GERD","Hyperacidity","Gastritis","Nausea & Vomiting"] },
  { name: "OrandOf", rx: true, composition: "Ofloxacin 200mg + Ornidazole 500mg", form: "Tablet", category: "tablets", area: "infection", image: "assets/products/orandof.jpg", use: "Anti-Infective (GI)", tags: ["Gastroenteritis","Acute Diarrhoea","Dysentery","Mixed GI Infections","Amoebic Infections"] },
  { name: "Plazolid-600", rx: true, composition: "Linezolid 600mg", form: "Tablet", category: "tablets", area: "infection", image: "assets/products/plazolid-600.jpg", use: "Anti-Infective", tags: ["Skin & Soft Tissue Infections","Community-Acquired Pneumonia","Diabetic Foot Infections","MRSA Infections"] },
  { name: "Pentapraz-DSR/40", rx: true, composition: "Pantoprazole 40mg (EC) + Domperidone 30mg (SR) Capsule; also available as Pantoprazole 40mg Injection", form: "Capsule / Injection", category: "tablets", area: "gastro", image: "assets/products/pentapraz-dsr-40.jpg", use: "Gastric Care", tags: ["Hyperacidity","Heartburn","GERD / Reflux Esophagitis","Peptic Ulcers","Duodenal Ulcers"] },
  { name: "Plaziron-XT", rx: false, composition: "Ferrous Ascorbate 100mg, Folic Acid 1.5mg, Zinc Sulphate 22.5mg, Cyanocobalamin 15mcg", form: "Tablet", category: "tablets", area: "bone", image: "assets/products/plaziron-xt.jpg", use: "Hematinic", tags: ["Iron Deficiency Anaemia","Pregnancy","Lactation","Menorrhagia","Generalised Weakness"], also: "Plaziron-XT Syrup — Ferrous Ascorbate 30mg, Folic Acid 550mcg/5ml" },
  { name: "Preplaz-Z", rx: true, composition: "Lactobacillus acidophilus 1.33B CFU, Lacticaseibacillus rhamnosus 0.72B CFU, Saccharomyces boulardii 0.50B CFU, Bifidobacterium longum 0.20B CFU, FOS 100mg, Zinc 7.5mg", form: "Capsule", category: "tablets", area: "gastro", image: "assets/products/preplaz-z.jpg", use: "Probiotic", tags: ["Antibiotic Associated Diarrhoea","Infectious Diarrhoea","Digestive Disorders","Recurrent Infections"] },
  { name: "Plazof-200", rx: true, composition: "Ofloxacin 200mg", form: "Tablet", category: "tablets", area: "infection", image: "assets/products/plazof-200.jpg", use: "Anti-Infective", tags: ["RTI","UTI","Skin & Soft Tissue Infections"] },
  { name: "Rabplaz-DSR", rx: true, composition: "Rabeprazole (EC) 20mg, Domperidone (SR) 30mg", form: "Capsule", category: "tablets", area: "gastro", image: "assets/products/rabplaz-dsr.jpg", use: "Gastric Care", tags: ["GERD","Hyperacidity"] },
  { name: "Rabplaz-LSR", rx: true, composition: "Rabeprazole (EC) 20mg, Levosulpiride (SR) 75mg", form: "Capsule", category: "tablets", area: "gastro", image: "assets/products/rabplaz-lsr.jpg", use: "Gastric Care", tags: ["Gastric Peptic Ulcer Disorders","Functional Dyspepsia","Diabetic Gastroparesis"] },
  { name: "Takeoff-MR", rx: true, composition: "Diclofenac 50mg, Paracetamol 325mg, Chlorzoxazone 250mg", form: "Tablet", category: "tablets", area: "pain", image: "assets/products/takeoff-mr.jpg", use: "Pain & Muscle Relaxant", tags: ["Low Back Pain","Sprain & Strains","Stiff Neck","Spondylitis","Myalgia","Frozen Shoulder"] },
  { name: "TryPlaz-BR", rx: true, composition: "Trypsin 40mg, Bromelain 90mg, Rutoside Trihydrate 100mg", form: "Tablet", category: "tablets", area: "pain", image: "assets/products/tryplaz-br.jpg", use: "Anti-Inflammatory", tags: ["Serious Traumatic Injury","Post Surgical Conditions","Dental Abscess","Arthritis"] },
  { name: "VitaPlaz-M", rx: true, composition: "Cyanocobalamin 1500mcg, Alpha Lipoic Acid 100mg, Pyridoxine HCl 3mg, Folic Acid 1.5mg", form: "Capsule", category: "tablets", area: "bone", image: "assets/products/vitaplaz-m.jpg", use: "Neuropathic Care", tags: ["Peripheral Neuropathy","Diabetic Neuropathy","Diabetic Retinopathy","Degenerative Diseases"] },
  { name: "VitaPlaz", rx: true, composition: "Ascorbic Acid 100mg, L-Lysine 20mg, Niacinamide 15mg, Zinc 10mg, Calcium Pantothenate 5mg with Multivitamin & Multimineral", form: "Capsule", category: "tablets", area: "bone", image: "assets/products/vitaplaz.jpg", use: "Multivitamin", tags: ["Nutritional Deficiencies","Weakness & Fatigue","Low Immunity","Recovery Support"], also: "VitaPlaz Drop — L-Lysine 50mg, Vit. C 40mg, L-Histidine 30mg, Taurine 15mg, Zinc 6.86mg & Multivitamin" },
  { name: "Telplaz-AM", rx: true, composition: "Telmisartan 40mg + Amlodipine 5mg", form: "Tablet", category: "tablets", area: "cardiac", image: "assets/products/telplaz-am.jpg", use: "Cardiac Care", tags: ["Hypertension","24-Hour BP Reduction"], also: "Telplaz-40 — Telmisartan 40mg" },
  { name: "D-Plaz", rx: true, composition: "Cholecalciferol 60,000 IU Softgel Capsule; Cholecalciferol 400 IU Drop", form: "Softgel / Drop", category: "tablets", area: "bone", image: "assets/products/d-plaz.jpg", use: "Vitamin D Supplementation", tags: ["Vitamin D Deficiency","Hyperlipidemia","Pregnancy & Lactation","Osteoporosis"] },

  // ===== SYRUPS & SUSPENSIONS =====
  { name: "CremaPlaz", rx: true, composition: "Liquid Paraffin 1.25ml + Milk of Magnesia 3.75ml + Sodium Picosulphate 3.33mg/5ml", form: "Suspension (200ml)", category: "syrups", area: "gastro", image: "assets/products/cremaplaz.jpg", use: "Digestive Care", tags: ["Piles","Anal Fissure","Hernia","Elderly & Bed-Ridden Patients"] },
  { name: "CyoPlaz", rx: true, composition: "Cyproheptadine HCl 2mg, Tricholine Citrate 275mg, Sorbitol Solution 2gm/5ml", form: "Syrup", category: "syrups", area: "bone", image: "assets/products/cyoplaz.jpg", use: "Appetite Stimulant", tags: ["Anorexia Nervosa","Sluggish Peristalsis","Indigestion"] },
  { name: "MucoTrust-SF", rx: true, composition: "Dextromethorphan HBr 10mg + Chlorpheniramine Maleate 4mg", form: "Sugar-Free Syrup", category: "syrups", area: "respiratory", image: "assets/products/mucotrust-sf.jpg", use: "Cough & Cold", tags: ["Dry Irritating Cough","Nasal Congestion","Seasonal Allergies","Common Cold"], also: "MucoTrust — same composition, regular syrup" },
  { name: "MucoTrust-AT", rx: false, composition: "Ambroxol HCl 15mg, Terbutaline 1.25mg, Guaiphenesin 50mg, Menthol 2.5mg/5ml", form: "Syrup", category: "syrups", area: "respiratory", image: "assets/products/mucotrust-at.jpg", use: "Cough & Respiratory Care", tags: ["Productive Cough","Asthmatic Cough","Smokers Cough","Emphysema"] },
  { name: "LivPlaz", rx: false, composition: "Ayurvedic Liver Tonic", form: "Syrup", category: "syrups", area: "gastro", image: "assets/products/livplaz.jpg", use: "Liver Care (Ayurvedic)", tags: ["Jaundice","Liver Cirrhosis","Fatty Liver Diseases","Chronic Alcoholic Patients"] },
  { name: "NimPlaz-MF", rx: true, composition: "Mefenamic Acid 100mg, Paracetamol 250mg", form: "Suspension", category: "syrups", area: "pain", image: "assets/products/nimplaz-mf.jpg", use: "Pediatric Pain & Fever", tags: ["Fever with Pain & Inflammation","Musculoskeletal Pain","Dental Pain"], also: "NimPlaz-250 — Paracetamol 250mg/5ml Suspension" },
  { name: "Plazyme", rx: true, composition: "Papain, Pepsin with Vitamin B Complex & L-Lysine", form: "Syrup", category: "syrups", area: "gastro", image: "assets/products/plazyme.jpg", use: "Digestive Aid", tags: ["Dyspepsia","Bloating","Flatulence","Belching"] },
  { name: "Pulselets", rx: true, composition: "Giloy 2000mg, Tulsi 1000mg, Amla 1000mg, Papaya Leaf 1000mg, Gokhru 500mg, Kalmegh 300mg, Punarnava 100mg, Fenugreek 50mg per 10ml", form: "Syrup (200ml)", category: "syrups", area: "ayurveda", image: "assets/products/pulselets.jpg", use: "Immune & Platelet Support (Ayurvedic)", tags: ["Supports Platelet Count","Dengue & Viral Infections","Immune Support","Post-Infection Recovery"] },
  { name: "StoPlaz", rx: true, composition: "Ayurvedic blend — Gokhru, Punarnava, Ikshumool, Varun, Shilapushpa, Pashanbhed, Durva, Daruhaldi, Chitrak, Guduchi, Shuddh Shilajit & more", form: "Syrup", category: "syrups", area: "ayurveda", image: "assets/products/stoplaz.jpg", use: "Urinary Care (Ayurvedic)", tags: ["Burning Micturition","Renal Calculi","Frequent Urination","Urinary Tract Infection"] },
  { name: "UriPlaz", rx: true, composition: "Ayurvedic Uterine Tonic (450ml)", form: "Syrup", category: "syrups", area: "women", image: "assets/products/uriplaz.jpg", use: "Women's Health (Ayurvedic)", tags: ["Dysmenorrhea","Puberty Menorrhagia","Irregular Cycles","Dysfunctional Uterine Bleeding"] },
  { name: "Placid-O", rx: true, composition: "Magaldrate 540mg, Simethicone 50mg, Oxetacaine 10mg", form: "Suspension", category: "syrups", area: "gastro", image: "assets/products/placid-o.jpg", use: "Gastric Care", tags: ["Hyperacidity","Belching","Gastritis","Heartburn","Indigestion"] },
  { name: "CidoPlaz-50", rx: true, composition: "Cefpodoxime Proxetil 50mg", form: "Dry Syrup", category: "syrups", area: "infection", image: "assets/products/cidoplaz-50.jpg", use: "Anti-Infective (Pediatric)", tags: ["Upper & Lower RTIs","Acute Otitis Media","Sinusitis"] },

  // ===== INJECTIONS =====
  { name: "DicPlaz-Aqua", rx: true, composition: "Diclofenac 75mg/ml + Benzyl Alcohol 4% v/v", form: "Injection", category: "injections", area: "pain", image: "assets/products/dicplaz-aqua.jpg", use: "Pain Management", tags: ["Post-Operative Pain","Trauma","Rheumatoid Arthritis","Osteoarthritis","Renal Colic","Dental Surgery"] },
  { name: "Plazone-S 1500", rx: true, composition: "Ceftriaxone 1000mg + Sulbactam 500mg", form: "Injection", category: "injections", area: "infection", image: "assets/products/plazone-s-1500.jpg", use: "Anti-Infective", tags: ["Bacteremia & Septicemia","Pneumonia & Bronchitis","Skin & Soft Tissue Infection","Post Surgical Condition"], also: "Plazone-1000 — Ceftriaxone 1000mg Injection" },
  { name: "VitaPlaz-M Forte", rx: true, composition: "Methylcobalamin 1500mcg, Pyridoxine HCl 100mg, Niacinamide 100mg", form: "Injection", category: "injections", area: "bone", image: "assets/products/vitaplaz-m-forte.jpg", use: "Neuropathic Care", tags: ["Postherpetic Neuralgia","Neuropathy","Muscle Cramps & Weakness","Spinal Cord Injury","Low Back Pain"], also: "VitaPlaz-M — Methylcobalamin 1000mcg 2ml Injection" },

  // ===== FORMULATIONS (nutraceuticals, ayurvedic, topical, drops, powder) =====
  { name: "LycoPlaz-G", rx: false, composition: "Green Tea Ext. 100mg + Grape Seed Ext. 10mg + Ginseng 21.25mg + Lycopene with Multivitamin & Multimineral", form: "Soft Gelatin Capsule", category: "formulations", area: "bone", image: "assets/products/lycoplaz-g.jpg", use: "Antioxidant / General Wellness", tags: ["Cardiac & Diabetic Protection","Neuro Protection","Fatigue & Stress Relief","Immunity & Stamina"], also: "LycoPlaz Syrup — Lycopene 1000mcg with Multivitamin & Multimineral" },
  { name: "ConstiPlaz", rx: false, composition: "Ayurvedic Constipation Powder", form: "Powder", category: "formulations", area: "gastro", image: "assets/products/constiplaz.jpg", use: "Digestive Care (Ayurvedic)", tags: ["Constipation","Diverticulosis","Anorectal Disease","Irritable Bowel Syndrome"] },
  { name: "ProtoPlaz", rx: false, composition: "DHA, GLA with Multivitamin & Multimineral Protein Powder", form: "Powder (Chocolate / Vanilla)", category: "formulations", area: "bone", image: "assets/products/protoplaz.jpg", use: "Nutrition", tags: ["Post-Operative Convalescence","Prolonged Illness","Pregnancy & Lactation","General Weakness","Malnutrition"] },
  { name: "OrthoPlaz", rx: true, composition: "Ayurvedic Pain Relief Oil", form: "Oil (50/100ml)", category: "formulations", area: "pain", image: "assets/products/orthoplaz.jpg", use: "Pain Relief (Ayurvedic)", tags: ["Pain & Sprain","Stiff & Swollen Joints","Arthritis","Frozen Shoulder"] },
  { name: "CampPlaz", rx: false, composition: "Carboxymethyl Cellulose 0.5% w/v + Oxychloro Complex 0.05% w/v", form: "Eye Drop", category: "formulations", area: "eye", image: "assets/products/camplaz.jpg", use: "Dry Eye Care", tags: ["Dry Eye Syndrome","Digital Eye Strain","Ocular Surface Lubrication"] },
  { name: "TobPlaz", rx: true, composition: "Tobramycin 0.3% w/v + Benzalkonium Chloride 0.01% w/v", form: "Eye Drop", category: "formulations", area: "eye", image: "assets/products/tobplaz.jpg", use: "Ophthalmic Anti-Infective", tags: ["Conjunctivitis","Blepharitis & Keratitis","External Ocular Infections"] },
  { name: "Moxiplaz", rx: true, composition: "Moxifloxacin 0.5% w/v", form: "Eye Drop", category: "formulations", area: "eye", image: "assets/products/moxiplaz.jpg", use: "Ophthalmic Anti-Infective", tags: ["Bacterial Conjunctivitis","Blepharitis & Keratitis","Corneal Ulcers","External Ocular Infections"] },
  { name: "Moxiplaz-D", rx: true, composition: "Moxifloxacin 0.5% w/v + Dexamethasone 0.1% w/v", form: "Eye Drop", category: "formulations", area: "eye", image: "assets/products/moxiplaz-d.jpg", use: "Ophthalmic", tags: ["Pre & Post Operative Surgery","Keratitis","Bacterial Conjunctivitis"], also: "Moxiplaz — Moxifloxacin 0.5% w/v Eye Drop" },
];

const CATEGORY_LABELS = {
  tablets: "Tablets & Capsules",
  syrups: "Syrups & Suspensions",
  injections: "Injections",
  formulations: "Formulations",
};

const AREA_LABELS = {
  pain: "Pain & Inflammation",
  infection: "Anti-Infective",
  cardiac: "Cardiac Care",
  respiratory: "Respiratory & Allergy",
  gastro: "Gastro & Liver Care",
  women: "Women's Health & Pregnancy",
  bone: "Bone, Nerve & Nutrition",
  eye: "Eye Care",
  ayurveda: "Ayurvedic Wellness",
};

const AREA_BLURBS = {
  pain: "Relief for musculoskeletal pain, inflammation, spasms and post-operative recovery.",
  infection: "Antibiotics and anti-infectives across respiratory, urinary, dental and skin infections.",
  cardiac: "Blood pressure and heart health formulations for daily cardiac care.",
  respiratory: "Allergy, cough, cold and asthma support for clearer breathing.",
  gastro: "Acidity, digestion, liver support and gut health across all ages.",
  women: "Pregnancy care, menstrual health and gynaecological wellness.",
  bone: "Calcium, vitamin D, neuropathy and everyday nutritional support.",
  eye: "Ophthalmic care for infection, inflammation and post-surgical recovery.",
  ayurveda: "Traditional herbal formulations for immunity, urinary and liver wellness.",
};

